language: c
compiler:
  - gcc
  - clang
# Change this to your needs
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libfuse-dev libxml2-dev dbench 
    nfs-common nfs-kernel-server xfsprogs 
    attr rpm yajl-tools 
before_install:
  - wget https://github.com/lpabon/cmockery2/archive/v1.3.8.tar.gz
  - tar -xvf v1.3.8.tar.gz
  - cd cmockery2-1.3.8 && ./autogen.sh && ./configure && make && sudo make install && cd ..
script: 
  - ./autogen.sh 
  - ./configure
  - make
  - sudo ./run-tests.sh

