language: c
compiler:
  - gcc
  - clang
# Change this to your needs
before_script:
  - sudo apt-get update -y
  - sudo apt-get install -y libfuse-dev libxml2-dev dbench 
    xfsprogs attr rpm yajl-tools nfs-kernel-server nfs-common python-mock
before_install:
  - wget https://github.com/lpabon/cmockery2/archive/v1.3.8.tar.gz
  - tar -xvf v1.3.8.tar.gz
  - cd cmockery2-1.3.8 && ./autogen.sh && ./configure && make && sudo make install && cd ..
  - git clone git://git.fedorahosted.org/git/mock.git mock
  - cd mock && ./autogen.sh && ./configure && make && sudo make install && cd ..
script:
   - echo "Since gerrit runs the regressions tests, why bother travis!"
#  - ./autogen.sh && ./configure && make && sudo make install
#  - sudo ./run-tests.sh
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "loaSEs7+//x5ssx1zM7XEbxnR/i+VendNLaWlUH3u3uD1oLm+LPhv1seS8zZ3a6AlxINEqXpH0NPjviig4aUOmJWvT9MHaRIR5Ym2xIfpSMKnCul6bEX2O6nCu4uiORZUb+CDnPjqQ8rAUugvvTqPj+CcMXljtQlIdlZQ6Luuio="

addons:
  coverity_scan:
    project:
      name: "nandajavarma/glusterfs"
      description: "GlusterFS clone"
    notification_email: nandaja.varma@gmail.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command:   "make"
    branch_pattern: "*"
